[manager]
show_hidden = true
show_symlink = true


 = true


 = true


 = true


 = true


 = true


 = true


 = true


 = true


 = true


 = true


 = true


 = true


 = true


 = true


 = true


 = true


 = true


 = true


 = true


 = true

